config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
      get :votes, :recommends
    end
  end

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/upload', to: 'gags#new'
  match '/uploadwithimage', to: 'gags#new2'
  match '/uploadvideo', to: 'gags#new3'
  match 'ups', to: 'static_pages#loginerror'
  match '/search', to: 'static_pages#search'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :gags, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :gaglikes, only: [:create, :destroy]
  resources :gagreports, only: [:create]
  resource :comments, only: [:create, :show, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/epic', to: 'gags#epic'
  match '/rising', to: 'gags#rising'
  match '/hatched', to: 'gags#hatched'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		if signed_in?
			@micropost = current_user.microposts.build
			@feed_items = current_user.feed.paginate(page: params[:page])
			@feed_items2= current_user.feed2.paginate(page: params[:page])
		end
	end

	def help
	end

	def about
	end

	def contact
	end

	def search
		@search=params[:term]
		search='%'+params[:term]+'%'
		@users=User.paginate(page: params[:page]).where('name like ?',search).all
		@gags=Gag.paginate(page: params[:page]).where('title like ?',search).all
		search='%#'+params[:term]+'%'
		@microposts=Micropost.paginate(page: params[:page]).where('content like ?', search).all

	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>

<div class="center hero-unit">
	<h1>Please note</h1>
	This app has a unfortunate dependencie on <%= link_to("ImageMagick", "http://www.imagemagick.org/script/index.php") %>
	And most probably will not run without it.
	
	<h2>ToDo list</h2>
	<ul>
		<li>Add file verification (on the signup form) </li>
		<li>Everything else, but first, a bit more functionality for the user</li>
	</ul>
</div>




<p>
	This web app is beeing build as a project for <a href="http://www.ius.edu.ba/Default.aspx?PageContentID=1766&tabid=1292">Special Topics in Computer Science</a>
	Work is in progres</p>
	So far done:
	
  <ul>
		<li>A few static pages, including the one you are visiting right now</li>
		<li>A whole lot of creation and deletion, the database migrations are a real mess</li>
		<li>User sign in/ sign out</li>
		<li>Cookies are enabled, permanent user sign in is achieved this way</li>
		<li>Implemented the ability for users to upload profile pictures</li>
		<li>Heavy usage of bootstrap to make it remotley attractive</li>
		<li>A bunch of small stuff, like the mail_to link in the footer</li>
		<li>Added a bunch of tests including factorygirls tests. Most of them are copied from the internet *blush*</li>
		<li>Added a first aid favicon, just for the fun of it</li>
	</ul>


app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact me about this app <%= mail_to "b.ttalic@gmail.com", "Benjamin Talic" %>
</p>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Feed') %>
<% if signed_in? %>
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
<div class="btn-group">
		<button class="btn btn-inverse" id="switch_to_gags">Gags (<%= @user.feed2.count %>)</button>
		<button class="btn btn-primary" id="switch_to_microposts">Microposts (<%= @user.feed.count %>)</button>	
	</div>
	</aside>

</br>

<div class="active"  id="gags">
	<div style="margin-left:10px;" class="span pull-right palette palette-concrete">
		<h3>Gags Feed</h3>
		<%= render 'shared/feed2' %>
	</div>
</div>

<div class="hidden"  id="microposts">
	<div class="span7 pull-right palette palette-concrete">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

</div>
<% else %>
<div class="center hero-unit">
	<h1>Welcome to Gags on Rails</h1>
	<h2>
		This is the index page for Gags on Rails. In the near future, or in a parallel universe there is a bunch of funny pictures on this page.
		For now, see the About page for the development log and see Sign up, that works :D
	</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<%= image_tag("hc.jpg", :size=>"100x64" ) %>
<% end %>

app/views/static_pages/loginerror.html.erb
<% provide(:title, 'Ups') %>
<div class="center hero-unit">
	<h1>Welcome to Gags on Rails</h1>
	<div class="alert alert-error"><h2>
		Seems like You will have to loggin to do that
	</h2>
</div>
<%= link_to "Sign in now!", signin_path, class: "btn btn-large btn-primary" %>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/search.html.erb
<div class="row">
	<h1>You searched for: <%="#{@search}"%></h1>


	<div id="users" class="span4">
		<h1>Users (<%=@users.length%>)</h1>
		<ul class="users">
			<%= render @users %>
		</ul>
	</div>

	<div id="microposts" class="span4 offset1">
		<h1>Microposts (<%=@microposts.length%>)</h1>
		<ul class="microposts">
			<%= render @microposts %>
		</ul>
	</div>

	<div id="gags" class="span3 offset2">
		<h1>Gags (<%=@gags.length%>)</h1>
		<ul class="users">
			<%= render @gags %>
		</ul>
	</div>


</div>