config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
      get :votes, :recommends
    end
  end

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/upload', to: 'gags#new'
  match '/uploadwithimage', to: 'gags#new2'
  match '/uploadvideo', to: 'gags#new3'
  match 'ups', to: 'static_pages#loginerror'
  match '/search', to: 'static_pages#search'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :gags, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :gaglikes, only: [:create, :destroy]
  resources :gagreports, only: [:create]
  resource :comments, only: [:create, :show, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/epic', to: 'gags#epic'
  match '/rising', to: 'gags#rising'
  match '/hatched', to: 'gags#hatched'

end

app/views/shared/_dislike.html.erb
<button class="btn btn-danger"><%= image_tag('no_transparent.png') %></button>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<%= will_paginate @feed_items, :params=>{"type"=>"micro"} %>
<%else%>
<div class="alert alert-warning">
					Nothing in your feed, add some followers!
			</div>
<% end %>

app/views/shared/_feed2.html.erb
<% if @feed_items2.any? %>
<ol class="gags">
	<%= render partial: 'shared/feed_item2', collection: @feed_items2 %>
</ol>
<%= will_paginate @feed_items2,  :params=>{"type"=>"gags"} %>
<%else%>
<div class="alert alert-warning">
	Nothing in your feed, add some followers!
</div>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<% if(feed_item.user.avatar?) %>
	<%= link_to image_tag(feed_item.user.avatar.url, class:"thumb_user"), feed_item.user %>
	<% else %>
	<%= link_to image_tag("user_default.png", class:"thumb_user"), feed_item.user %>
	<% end %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"  id="micropostcontent"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
		
		<% if current_user?(feed_item.user) %>
		<%= link_to "delete", feed_item, method: :delete,
		confirm: "You sure?",
		title: feed_item.content %>
		<% end %>

		
	</span>
</li>

app/views/shared/_feed_item2.html.erb
<li id="<%= feed_item2.id %>">
	
	
	<span class="span2 pull-right gag_title"> <%= link_to feed_item2.title, feed_item2 %>
	</br>
	<span class="timestamp">
		<%= time_ago_in_words(feed_item2.created_at) %> ago.
		By <%= link_to feed_item2.user.name, feed_item2.user %>
		<% if current_user?(feed_item2.user.name) %>
		<%= link_to "delete", feed_item2, method: :delete,
		confirm: "You sure?",
		title: feed_item2.title %>
		<% end %>
		
	</span>
</br>
	<span class="like-status">
<%= image_tag('megusta.png') %>
</span>
<span id="votes<%="#{feed_item2.id}"%>" class="like-status">
	<%= feed_item2.votes_up %>
</span>
<span class="like-status">
	<%= image_tag('comment.png') %>
</span>
<span class="like-status">
	<%= feed_item2.comments.count %>
</span>
<div>
<%= render :partial=>'gags/like',  :locals => {:like => feed_item2, :counter=>feed_item2_counter} %>
</div>
	<div>
	<%= render :partial=>'gags/report', :locals => {:report => feed_item2} %>
</div>
</span>

<span> 
	<% if(feed_item2.image?) %>
	<%= link_to image_tag(feed_item2.image.url, :id=>"gag#{feed_item2_counter}"), feed_item2 %>
	<% elsif feed_item2.imagelink? %>
	<%= link_to image_tag(feed_item2.imagelink, :id=>"gag#{feed_item2_counter}"), feed_item2 %>
	<% else %>
	<iframe width="460" height="275" src="<%= feed_item2.videolink %>" frameborder="0" allowfullscreen></iframe>
	<% end %>

</span>
</li>


app/views/shared/_like.html.erb
<button class="btn btn-success"><%= image_tag('megusta_transparent.png') %></button>

app/views/shared/_like_form.html.erb
<div id="follow_form">
<% if current_user.liked?(gag) %>
<%= render 'like' %>
<% else %>
<%= render 'dislike' %>
<% end %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<%= f.text_area :content, placeholder: "Compose new micropost..." %>
</div>
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_mostliked.html.erb
<% if @mostliked %>
<%if current_user.theme==2 %>
<div class="pull-right  palette palette-info-dark " style="margin-top:10px; width: 236px;">
<%else %>
<div class="pull-right  recommended_users " >
<%end%>


<h4>Most Liked</h4>

<%= render partial: 'shared/mostliked_item', collection: @mostliked %>

<%else%>
<div class=" pull-right recommended_users" >
<h4>Mostliked</h4>
<%end%>
</div>

app/views/shared/_mostliked_item.html.erb

	<% if(mostliked_item.image?) %>
	<%= link_to image_tag(mostliked_item.image.url(:thumb), class:"show_follow_thumb_user"), mostliked_item %>
	<% elsif mostliked_item.imagelink?  %>
	<%= link_to image_tag(mostliked_item.imagelink, class:"show_follow_thumb_user"), mostliked_item %>
	<%else%>
	<%= link_to image_tag('video.png',class:"show_follow_thumb_user"), mostliked_item %>
	<% end %>

app/views/shared/_recommend_item.html.erb

	<% if(recommend_item.avatar?) %>
	<%= link_to image_tag(recommend_item.avatar.url, class:"show_follow_thumb_user"), recommend_item %>
	<% else %>
	<%= link_to image_tag("user_default.png", class:"show_follow_thumb_user"), recommend_item %>

	<% end %>

app/views/shared/_recommends.html.erb
<% if signed_in?%>
<%if current_user.theme==2 %>
<div class="pull-right  palette palette-info-dark " style="width: 236px;"  >
<%else %>
<div class="pull-right  recommended_users " >
<%end%>

<% if @recommends.count>0 %>
<h4>Recommended Users</h4>

<%= render partial: 'shared/recommend_item', collection: @recommends %>

<%else%>

<h4>No recommendations</h4>
<%end%>
</div>
<%else%>
<div class="pull-right  recommended_users " >
<h4>No recommendations</h4>
</div>
<%end%>

app/views/shared/_stats.html.erb
<div class="palette palette-pomegranate">
<% @user ||= current_user %>
<div class="stats ">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>

	<a href="<%= votes_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.gaglikes.count %>
		</strong>
		votes
</div>	</a>


app/views/shared/_user_info.html.erb
<div class="palette palette-alizarin">
<a href="<%= user_path(current_user) %>">
	<% if(current_user.avatar?) %>
		<%= image_tag current_user.avatar.url(), class:"avatar" %>
		<% else %>
		<%= image_tag ("user_default.png"), class:"avatar" %>
		<% end %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
	|
	<%= pluralize(current_user.gags.count, "gag") %>
</span>
</div>