config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
      get :votes, :recommends
    end
  end

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/upload', to: 'gags#new'
  match '/uploadwithimage', to: 'gags#new2'
  match '/uploadvideo', to: 'gags#new3'
  match 'ups', to: 'static_pages#loginerror'
  match '/search', to: 'static_pages#search'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :gags, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :gaglikes, only: [:create, :destroy]
  resources :gagreports, only: [:create]
  resource :comments, only: [:create, :show, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/epic', to: 'gags#epic'
  match '/rising', to: 'gags#rising'
  match '/hatched', to: 'gags#hatched'

end

app/models/gag.rb
class Gag < ActiveRecord::Base
  attr_accessible  :title, :image, :votes_up, :imagelink, :videolink
  #:ratio, :title, :user_id, :votes, :votes_up, :image
  has_attached_file :image, dependent: :destroy, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, 
  :content_type => /^image\/(png|gif|jpeg)/
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 },
  uniqueness: { case_sensitive: false }

  has_many :comments, foreign_key: "gag_id", dependent: :destroy

  validate :at_least_one
  validate :videolink_format
  validate :imagelink_format

  def at_least_one
    if [self.image, self.imagelink, self.videolink].compact.size == 0
      errors[:base] << ("You must add a Gag")
    end
  end 

  def videolink_format
    if self.videolink?
     if (self.videolink.include?("youtube") && self.videolink.include?("v="))==false
      errors[:base] << ("Invalid video link")
    else
      self.videolink="http://www.youtube.com/embed/"+self.videolink[self.videolink.index("v=")+2, self.videolink.length]
    end
  end
end

def imagelink_format
  if self.imagelink?

    if( self.imagelink.include?(".gif") || self.imagelink.include?(".png") || self.imagelink.include?(".jpg") || self.imagelink.include?(".jpeg") )==false
      errors[:base] << ("Invalid image link")
    end
  end
end

#gaglike
has_many :gaglikes, foreign_key: "liked_id", dependent: :destroy
has_many :gagreports, foreign_key: "reported_id", dependent: :destroy

default_scope order: 'gags.created_at DESC'



def self.from_users_followed_by(user)
  followed_user_ids = "SELECT followed_id FROM relationships
  WHERE follower_id = :user_id"
  where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
   user_id: user.id)
end



end

app/controllers/gags_controller.rb
class GagsController < ApplicationController
 before_filter :signed_in_user, :except=>[:epic, :rising, :hatched, :show]
 # before_filter :correct_user,   only: :destroy


 def new
  @gag=Gag.new
end

def new2
  @gag=Gag.new
end

def new3
  @gag=Gag.new
end

def show
  @gag=Gag.find(params[:id])
  @comments=Comment.order('created_at DESC').find_all_by_gag_id(params[:id])
end

def create
  @gag = current_user.gags.build(params[:gag])
  @gag.votes_up=1
  @gag.votes=1
  @gag.ratio=1
  if @gag.save
    flash[:success] = "Awwwwwww Yeah! Thanks for the smiles"
    current_user.like!(@gag)
    redirect_to current_user
  else
    if request.referer.include?("uploadvideo")
      render 'new3'
    elsif request.referer.include?("uploadwithimage")
      render 'new2'
    else
      render 'new'
    end

  end
end

def destroy
  flash[:success] = "Gag deleted!"
  @gag=Gag.find(params[:id]).destroy
  redirect_to request.referer
end

def epic
  @epic=Gag.paginate(page: params[:page], :per_page=>100).find(:all, :conditions=>['votes>=200 and ratio>=0.3'])
  if signed_in?
  getRecommends
  getMostliked
end
end

def rising
  @rising=Gag.paginate(page: params[:page], :per_page=>100).find(:all, :conditions=>['(votes<200 and votes>=100 and ratio>0.15) '])
  if signed_in?
  getRecommends
  getMostliked
end
end

def hatched
  @hatched=Gag.paginate(page: params[:page], :per_page=>100).find(:all, :conditions=>['ratio<0.15 or votes<100 '])
  if signed_in?
  getRecommends
  getMostliked
end
end

def getMostliked
  @mostliked=Gag.find(:all, :order => "votes_up desc", :limit => 5)
end

def getRecommends
  gaglikes=current_user.gaglikes
  liked_ids=gaglikes.pluck(:liked_id)
  others=Gaglike.find_all_by_liked_id_and_vote_sign(liked_ids, "1")
  others_ids=Array.new
  others.first(10).each do |gag|
    if gag.liker_id!=current_user.id
      others_ids.push(gag.liker_id)
    end
  end
  @recommends=User.find_all_by_id(others_ids)
end

private

def correct_user
  @gag=Gag.find(params[:id])
  redirect_to(root_url) unless current_user?(@gag.user)
end

end

app/views/gags/_add_comment.html.erb
<% if signed_in? %>
<%= form_for(current_user.comments.build(gag_id: @gag.id),
	remote: true) do |f| %>
	<%= f.hidden_field :gag_id %>
	<%= f.text_field :content %>
	
	<%= f.button "Add Comment", class:"btn btn-primary pull-right" %>
	
<% end %>
<%else %>
	<input type="textarea" />
	<a href='/ups'><%= button_tag("Add Comment", class:"btn btn-primary pull-right") %></a>
<%end%>

app/views/gags/_gag.html.erb
<li >
	<% if gag_counter%2==0 %>
	<div class=" palette palette-night">
		<%else%>
		<div class=" palette palette-night-dark">
			<% end %>
			<% if !request.fullpath.include? '/search' %>
			<% if gag_counter%2==0 %>
			<asside class="pull-right gag_title palette palette-night-dark" style="width:153px"> <%= link_to gag.title, gag %>
				<% else %>
				<asside class="pull-right gag_title palette palette-night" style="width:153px"> <%= link_to gag.title, gag %>
					<% end %>

			<span class="timestamp">
				<%= time_ago_in_words(gag.created_at) %> ago.

				<% if current_user?(gag.user) %>
				<%= link_to "delete", gag, method: :delete,
				confirm: "You sure?",
				title: gag.title %>
				<% end %>
			</span>
		</br>
		<span class="like-status">
			<%= image_tag('megusta.png') %>
		</span>
		<span id="votes<%="#{gag.id}"%>" class="like-status">
			<%= gag.votes_up %>
		</span>
		<span class="like-status">
			<%= image_tag('comment.png') %>
		</span>
		<span class="like-status">
			<%= gag.comments.count %>
		</span>
		<div>
			<%= render :partial=>'gags/like', :locals => {:like => gag, :counter=>gag_counter} %>

		</div>

		<div>
			<%= render :partial=>'gags/report', :locals => {:report => gag} %>
		</div>

		

	</asside>
	<%else %>
		<% if gag_counter%2==0 %>
			<div class="gag_title palette palette-night-dark" style="width:153px"> <%= link_to gag.title, gag %>
		<% else %>
			<div class=" gag_title palette palette-night" style="width:153px"> <%= link_to gag.title, gag %>
		<% end %>
		</br>
	<%end%>

		<span>
			<% if(gag.image?) %>
			<%= link_to image_tag(gag.image.url, :id=>"gag#{gag_counter}"), gag %>
			<% elsif gag.imagelink? %>
			<%= link_to image_tag(gag.imagelink, :id=>"gag#{gag_counter}"), gag %>
			<% else %>
			<iframe width="460" height="275" src="<%= gag.videolink %>" frameborder="0" allowfullscreen></iframe>
			<% end %>
		</span>
	</div>

</li>

app/views/gags/_like.html.erb

<% if signed_in? %>
<span id="gaglikes_form<%="#{like.id}"%>" class="span2 votes form-group btn-group btn-toggle">
	<%= form_for(current_user.gaglikes.build(liked_id: like.id, vote_sign:"1"),
	remote: true,  :html=>{:id=>"like#{counter}"}) do |f| %>
	<%= f.hidden_field :liked_id %>
	<%= f.hidden_field :vote_sign %>
	<% if current_user.liked?(like) %>
	<%= f.button image_tag('megusta_transparent.png'),  class:"btn btn-success", :id=>"#{like.id}"+"up" %>
	<% else %>
	<%= f.button image_tag('megusta_transparent.png'), class:"btn btn-success not-clicked-like-dislike", :id=>"#{like.id}"+"up" %>
	<% end %>
	<% end %>
	
	<%= form_for(current_user.gaglikes.build(liked_id: like.id, vote_sign:"-1"),
	remote: true ,  :html=>{:id=>"dislike#{counter}"}) do |f| %>
	<%= f.hidden_field :liked_id %>
	<%= f.hidden_field :vote_sign %>
	<% if current_user.disliked?(like) %>
	<%= f.button image_tag('no_transparent.png'), class:"btn btn-danger" %>
	<% else %>
	<%= f.button image_tag('no_transparent.png'), class:"btn btn-danger not-clicked-like-dislike", :id=>"#{like.id}"+"down" %>
	<% end %>
	<% end %>

	<%else %>
	<span  class="span2 votes form-group btn-group">
		<a href='/ups'><%= button_tag image_tag('megusta_transparent.png'), class:"btn btn-success not-clicked-like-dislike", :id=>"#{like.id}"+"up" %></a>
		<a href='/ups'><%= button_tag image_tag('no_transparent.png'), class:"btn btn-danger not-clicked-like-dislike", :id=>"#{like.id}"+"down" %></a>
	</span>
		<%end%>

	</span>

app/views/gags/_report.html.erb
<% if signed_in? %>

<span id="gagreports_form<%="#{report.id}"%>" class="span2 votes form-group btn-group btn-toggle">
<% if !current_user.reported?(report) %>
	<%= form_for(current_user.gagreports.build(reported_id: report.id, report_type:"1")) do |f| %>
	<%= f.hidden_field :reported_id %>
	<%= f.hidden_field :report_type %>

	<%= f.button "Report repost!",  class:"btn btn-mini btn-danger" %>

	<% end %>

<%= form_for(current_user.gagreports.build(reported_id: report.id, report_type:"2")) do |f| %>
	<%= f.hidden_field :reported_id %>
	<%= f.hidden_field :report_type %>
	
	<%= f.button "Report inappropriate!",  class:"btn btn-mini btn-danger" %>

	<% end %>
<%end%>
TEEEES
</span>
	<%end%>

app/views/gags/_show_comments.html.erb
<ul id="comments" >
<% @comments.each do |comment| %>
<li class="comment">
	<span class="pull-left">
		<%if comment.user.avatar? %>
		<%= image_tag(comment.user.avatar.url, class:"show_follow_thumb_user") %>
		<%else%>
		<%= image_tag("user_default.png",class:"show_follow_thumb_user") %>
		<%end%>
	</br>
		<%= link_to comment.user.name, comment.user %>
	</span>
	<%=comment.content%>
	<div class="timestamp">
		<%= time_ago_in_words(comment.created_at) %> ago.

		<% if current_user?(comment.user) %>
		<%= link_to "delete", comments_path(id:comment.id), method: :delete,
		confirm: "You sure?" %>
		<% end %>
	</div>
</li>
<%end%>
</ul

app/views/gags/epic.html.erb
<%= provide(:title, 'Epic') %>
<div class="row">
	<% if @epic.any? %>
	<div class="span">
		<ol class="gags">
			<%= render @epic %>
		</ol>
		<%= will_paginate @epic %>
	</div>
	<% else %>
	<div class="alert alert-warning">
		Seems like there are no Gags for this section
	</div>
	<% end %>
</div>

app/views/gags/hatched.html.erb
<%= provide(:title, 'Hatched') %>
<div class="row">
	<% if @hatched.any? %>
	<div class="span">
		<ol class="gags">
			<%= render @hatched %>
		</ol>
		<%= will_paginate @hatched %>
	</div>
	<% else %>
	<div class="alert alert-warning">
		Seems like there are no Gags for this section
	</div>
	<% end %>
	<asside >
<%= render partial: 'shared/recommends' %>
<%= render partial: 'shared/mostliked' %>
</asside>
</div>

app/views/gags/new.html.erb
<%= provide(:title, 'Upload Gag') %>
<h1>Add Gag</h1>
<div class="row">
	<div class="span6">
		<%= form_for @gag, :html => { :multipart => true }  do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label :imagelink %><a href='/uploadwithimage'>Upload image</a>
		<%= f.text_field  :imagelink %>
	</br>
	<%= f.submit "Upload Gag", class: "btn btn-large btn-primary" %>
	<% end %>
	

</div>

<asside>
	<div class="span4 pull-right alert alert-warning">
		<h5>Submission rules</h5>
		<ul>
			<li>Respect originality and creativity. Try using Google Images to find the origin of the post.</li>
			<li>Think of an original or descriptive title, instead of phrases like "LOL", "True", or "AMAZING!"...</li>
			<li>No blogspam. Many, many sites just recycle pics from other sites and put ads on it.</li>
		</ul>
	</div>
</asside>
</div>

app/views/gags/new2.html.erb
<%= provide(:title, 'Upload Gag') %>
<h1>Add Gag</h1>
<div class="row">
	<div class="span6">
		<% unless request.host.include? "heroku" %>
		<%= form_for @gag, :html => { :multipart => true }  do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label :image %>
		<%= f.file_field  :image %>
	</br>
	<%= f.submit "Upload Gag", class: "btn btn-large btn-primary" %>
	<% end %>
	<%else%>
	<form accept-charset="UTF-8"  class="new_gag" method="post" disabled >
		
		<label for="gag_title">Title</label>
		<input id="gag_title" name="gag[title]" size="30" type="text">
		<label for="gag_image">Image</label>
		<input id="gag_image" name="gag[image]" type="file">
	</form>
</br>
<div class="alert alert-warning">This app is currently hosted on a free server which does not permit file upload. Use the other form to submit your Gag! </div>

<%end%>

</div>

<asside>
	<div class="span4 pull-right alert alert-warning">
		<h5>Submission rules</h5>
		<ul>
			<li>Respect originality and creativity. Try using Google Images to find the origin of the post.</li>
			<li>Think of an original or descriptive title, instead of phrases like "LOL", "True", or "AMAZING!"...</li>
			<li>No blogspam. Many, many sites just recycle pics from other sites and put ads on it.</li>
		</ul>
	</div>
</asside>
</div>

app/views/gags/new3.html.erb
<%= provide(:title, 'Upload Gag') %>
<h1>Add Gag</h1>
<div class="row">
	<div class="span6">
		<%= form_for @gag, :html => { :multipart => true }  do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label :videolink %>
		<%= f.text_field  :videolink %>
	</br>
	<%= f.submit "Upload Gag", class: "btn btn-large btn-primary" %>
	<% end %>
	

</div>

<asside>
	<div class="span4 pull-right alert alert-warning">
		<h5>Submission rules</h5>
		<ul>
			<li>Respect originality and creativity. Try using Google Images to find the origin of the post.</li>
			<li>Think of an original or descriptive title, instead of phrases like "LOL", "True", or "AMAZING!"...</li>
			<li>No blogspam. Many, many sites just recycle pics from other sites and put ads on it.</li>
		</ul>
	</div>
</asside>
</div>

app/views/gags/rising.html.erb
<%= provide(:title, 'Rising') %>
<div class="row">
	<% if @rising.any? %>
	<div class="span">
		<ol class="gags">
			<%= render @rising %>
		</ol>
		<%= will_paginate @rising %>
	</div>
	<% else %>
	<div class="alert alert-warning">
		Seems like there are no Gags for this section
	</div>
	<% end %>
</div>

app/views/gags/show.html.erb
<% provide(:title, @gag.title) %>
<div class="row">
	<div class="span10">
		<div class="gag-show-info">
		<div class="palette palette-asbestos">
			<span class="gag_title"><h1> <%= @gag.title %> </h1> <h4>By <%= link_to @gag.user.name, @gag.user %></h4></span>
		</br>
		<div class="btn-toolbar">
			<span class="form-group pull-right btn-group">
				<div>	
					<%= render :partial=>'gags/like',  :locals => {:like => @gag, :counter=>0} %>
				</div>
				
			</span>
		</div>
		<span class="like-status">
			<%= image_tag('megusta.png') %>
		</span>
	
		<span id="votes<%="#{@gag.id}"%>" class="like-status">
			<%= @gag.votes_up %>
		</span>
		<span class="like-status">
	<%= image_tag('comments.png') %>
</span>
<span class="like-status">
	<%= @gag.comments.count %>
</span>
	|
		<% if current_user?(@gag.user) %>
		<%= link_to " delete", @gag, method: :delete,
		confirm: "You sure?",
		title: @gag.title %>
		<% end %>	
	</div>
	</div><!--end gag-show-info-->

	<div style="width:780px">
		<% if(@gag.image?) %>
		<%= link_to image_tag(@gag.image.url, :id=>"gag#{@gag_counter}",:class => "gag-show"), @gag.image.url %>
		<% elsif @gag.imagelink? %>
		<%= link_to image_tag(@gag.imagelink, :id=>"gag#{@gag_counter}",:class => "gag-show"), @gag.imagelink %>
		<% else %>
		<iframe height="390" src="<%= @gag.videolink %>" frameborder="0" allowfullscreen class="gag-show"></iframe>
		<% end %>
	</div>
	<div class="add-comment">
		<h4>Comments</h4>
	<%= render 'add_comment' %>
</div>
<%= render 'show_comments', collection: @comments %>
</div>

</div>
</div>