config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
      get :votes, :recommends
    end
  end

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/upload', to: 'gags#new'
  match '/uploadwithimage', to: 'gags#new2'
  match '/uploadvideo', to: 'gags#new3'
  match 'ups', to: 'static_pages#loginerror'
  match '/search', to: 'static_pages#search'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :gags, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :gaglikes, only: [:create, :destroy]
  resources :gagreports, only: [:create]
  resource :comments, only: [:create, :show, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/epic', to: 'gags#epic'
  match '/rising', to: 'gags#rising'
  match '/hatched', to: 'gags#hatched'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%= link_to "Gags On Rails", root_path %>
		by
		<%= mail_to "b.ttalic@gmail.com", "Benjamin Talic" %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", about_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "GoR", root_path, id: "logo", class:"brand" %>
			<nav>
				<ul class="nav pull-left">
					<li><%= link_to "Epic", "/epic" %></li>
					<li><%= link_to "Rising", "/rising" %></li>
					<li><%= link_to "Hatched", "/hatched" %></li>
					<li>
						<%= form_tag('/search',:class=>"navbar-form nav-search", :method=>'post') do %>
						<%= text_field_tag(:term, nil, :placeholder =>"Search...") %>
						<% end %>

					</li>
				</ul>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<% if signed_in? %>
					<% if current_user.admin? %>
					<li><%= link_to "Users", users_path %></li>
					<%end%>

					<li id="fat-menu2" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Upload Gag <b class="caret"></b>
						</a>
						<%if current_user.theme==2%>
						<ul>
							<%else%>
							<ul class="dropdown-menu">
								<%end%>
								<li><%= link_to "Upload Image", '/uploadwithimage' %></li>
								<li><%= link_to "Add Image link", '/upload' %></li>
								<li><%= link_to "Add Video link", '/uploadvideo' %></li>
							</ul>



							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<%= current_user.name %> <b class="caret"></b>
								</a>
								<%if current_user.theme==2%>
								<ul>
									<%else%>
									<ul class="dropdown-menu">
										<%end%>
										<li><%= link_to "Profile", current_user %></li>
										<li><%= link_to "Settings", edit_user_path(current_user) %></li>
										<li class="divider"></li>
										<li>
											<%= link_to "Sign out", signout_path, method: "delete" %>
										</li>
									</ul>


								</li>
								<% else %>
								<li>
									<%= form_for(:session, url: sessions_path, :html=>{:class=>"navbar-form pull-right"}) do |f| %>
									<%= f.text_field :email, :value=>@email, class:"span2" %>
									<%= f.password_field :password, :value=>@password, class:"span2" %>
									<%= f.submit "Sign in", class: "btn btn-primary" %>
									<% end %>
								</li>
								<li>
									<%= form_tag(signup_path,  :class=>"navbar-form pull-right", :style=>"margin-left:-25px;") do %>
									<%= text_field_tag('request', nil, :class =>"span2 hidden ", :style=>"display:none") %>
									<%= submit_tag "Sign up", class: "btn btn-warning" %>
									<% end %>
									
								</li>

								<% end %>
							</ul>
						</nav>
					</div>
				</div>
			</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head >
	<%= favicon_link_tag 'favicon.ico' %>
	<title><%= full_title(yield(:title)) %></title>

	

<%= stylesheet_link_tag "application-all", media: "all" %>

	<% if signed_in? %>
	<%if current_user.theme==2%>
	<%= stylesheet_link_tag 'flat-ui' %>
	<%end%>
	<%end%>
	<%= stylesheet_link_tag 'zcustom' %>
	

	<%= javascript_include_tag "application" %>
	
	
	
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body >
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<!--the next beautiful piece of code allows me for on sote debuging-->
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>